# Generated by Django 3.2.4 on 2022-06-02 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResourceThroughTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('resources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.resource')),
            ],
            options={
                'ordering': ('topic', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(max_length=100)),
                ('relatedResources', models.ManyToManyField(blank=True, through='framework.ResourceThroughTopic', to='framework.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='TopicThroughTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('subtopics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='framework.topic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='framework.topic')),
            ],
            options={
                'ordering': ('topic', 'order'),
            },
        ),
        migrations.CreateModel(
            name='TopicThroughSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='framework.skill')),
                ('topics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='framework.topic')),
            ],
            options={
                'ordering': ('skill', 'order'),
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='relatedTopics',
            field=models.ManyToManyField(blank=True, related_name='_framework_topic_relatedTopics_+', through='framework.TopicThroughTopic', to='framework.Topic'),
        ),
        migrations.AddField(
            model_name='skill',
            name='relatedTopics',
            field=models.ManyToManyField(blank=True, through='framework.TopicThroughSkill', to='framework.Topic'),
        ),
        migrations.AddField(
            model_name='resourcethroughtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.topic'),
        ),
    ]
