# Generated by Django 3.2.4 on 2022-06-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='relatedTopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='framework.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
