# Generated by Django 3.2.4 on 2022-06-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0002_auto_20220601_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_name',
            new_name='topicName',
        ),
    ]
