# Generated by Django 3.2.4 on 2022-06-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0002_auto_20220602_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resourceName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
