# Generated by Django 3.2.4 on 2022-06-01 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0003_rename_topic_name_topic_topicname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceThroughTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('whichResource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.resource')),
                ('whichTopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.topic')),
            ],
            options={
                'ordering': ('whichTopic', 'order'),
            },
        ),
    ]
