# Generated by Django 3.2.4 on 2022-06-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0003_resource_resourcename'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='orderwrttopic',
            field=models.IntegerField(null=True),
        ),
    ]
