# Generated by Django 3.2.4 on 2022-05-25 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0004_auto_20220525_0119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.AlterModelOptions(
            name='superskill',
            options={},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='order',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='order',
        ),
        migrations.RemoveField(
            model_name='superskill',
            name='order',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='order',
        ),
    ]
