# Generated by Django 3.2.4 on 2022-06-03 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0004_resource_orderwrttopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='orderwrttopic',
        ),
    ]
