# Generated by Django 3.2.4 on 2022-06-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0005_topic_relatedresources'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcethroughtopic',
            options={'ordering': ('topic', 'order')},
        ),
        migrations.RenameField(
            model_name='resourcethroughtopic',
            old_name='whichResource',
            new_name='resources',
        ),
        migrations.RenameField(
            model_name='resourcethroughtopic',
            old_name='whichTopic',
            new_name='topic',
        ),
    ]
