# Generated by Django 3.2.4 on 2022-05-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0005_auto_20220525_0600'),
    ]

    operations = [
    ]
