# Generated by Django 3.2.4 on 2022-06-02 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0006_auto_20220601_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='order',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='relatedTopic',
        ),
    ]
