# Generated by Django 3.2.4 on 2022-06-02 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0007_auto_20220602_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='relatedResources',
            field=models.ManyToManyField(blank=True, through='framework.ResourceThroughTopic', to='framework.Resource'),
        ),
        migrations.CreateModel(
            name='TopicThroughTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('subtopics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='framework.topic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='framework.topic')),
            ],
            options={
                'ordering': ('topic', 'order'),
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='relatedTopics',
            field=models.ManyToManyField(blank=True, related_name='_framework_topic_relatedTopics_+', through='framework.TopicThroughTopic', to='framework.Topic'),
        ),
    ]
