# Generated by Django 3.2.4 on 2022-05-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0007_auto_20220525_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
