# Generated by Django 3.2.4 on 2022-05-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0008_alter_resource_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('sort_order',)},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='order',
        ),
        migrations.AddField(
            model_name='resource',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True),
        ),
    ]
