# Generated by Django 3.2.4 on 2022-05-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0009_auto_20220525_0654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AlterModelOptions(
            name='superskill',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AddField(
            model_name='skill',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='superskill',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True),
        ),
    ]
