# Generated by Django 3.2.4 on 2022-05-26 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0010_auto_20220525_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='relatedTopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='framework.topic'),
        ),
    ]
