# Generated by Django 3.2.4 on 2022-05-26 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0011_resource_relatedtopic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('sort_order', 'relatedTopic')},
        ),
        migrations.AlterField(
            model_name='resource',
            name='relatedTopic',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='framework.topic'),
        ),
    ]
