# Generated by Django 3.2.4 on 2022-05-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0013_auto_20220526_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcetotopic',
            options={'ordering': ('topic', 'sort_order')},
        ),
        migrations.AddField(
            model_name='resourcetotopic',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True),
        ),
    ]
